### ISSUE TITLE
[FR] Adding Setting for more styles (And share some rune styles)

### ISSUE THREAD

**Issue by Moyf** [Shusako/arcane-obfuscate#1]
It's a very interesting Plugin! Really like it!

And I'm thinking could you add an option to set the text color, and even the light color?

I use Color Snippets did this:

![26755cf7-0f0c-440a-844e-a48118d14cc6](https://github.com/user-attachments/assets/72055751-d08c-41eb-b17b-6f0416fc95ec)

css:
```css

.arcane-word,
.arcane-character {
    color: #ddcb96;
    text-shadow: 
        0 0 5px rgba(255, 255, 255, 0.8), /* 白色发光 */
        0 0 10px rgba(255, 255, 255, 0.6), /* 更模糊的白色发光 */
        0 0 15px rgba(52, 152, 219, 0.8), /* 蓝色发光 */
        0 0 20px rgba(52, 152, 219, 0.6); /* 更模糊的蓝色发光 */
}

```

There must be more ways to optimize styles; this is just a starting point!

---

*Updated*:
Another style:
![image](https://github.com/user-attachments/assets/fc1b0b1b-73d9-40a3-9020-a9991254e423)

```css
.arcane-word,
.arcane-character {
    color: rgb(225, 235, 245);

    text-shadow: 
        0 0 5px rgba(46, 186, 241, 0.8), /* 白色发光 */
        0 0 10px rgba(255, 255, 255, 0.6), /* 更模糊的白色发光 */
        0 0 15px rgba(0, 43, 126, 1.0), /* 蓝色发光 */
        0 0 20px rgb(58, 106, 202); /* 更模糊的蓝色发光 */
}

```

**Comment by Moyf** [comment]
BTW, with DynamicHighlight Plugin, it could make the texst in Live Editing mode also has style:
![image](https://github.com/user-attachments/assets/1483ecec-6499-4be9-8ba7-889a8069e902)

````css fold
.obfuscate-rune {
    color: black;
    color: rgb(225, 235, 245);
    text-shadow: 
        0 0 5px rgba(46, 186, 241, 0.8), /* 白色发光 */
        0 0 10px rgba(255, 255, 255, 0.6), /* 更模糊的白色发光 */
        0 0 15px rgba(0, 43, 126, 1.0), /* 蓝色发光 */
        0 0 20px rgb(58, 106, 202); /* 更模糊的蓝色发光 */
}
````

Live Editing Mode:
![image](https://github.com/user-attachments/assets/29d19282-30a8-4332-9203-de91b4c3fd70)

**Comment by Moyf** [comment]
Another Sytle: **Matrix**

![b14585e2-650c-4f7e-8703-38dd36b1dd73](https://github.com/user-attachments/assets/0cbca762-0168-4ab7-be01-3b170fa2af8b)

Character Set:
`⁰¹²³⁴⁵⁶⁷⁸⁹₀₁₂₃₄₅₆₇₈₉`

CSS:
```css

/* Matrix */
.arcane-word,
.arcane-character,
.obfuscate-rune {
    /* color: #ddcb96; */
    width: unset;
    color: rgb(225, 245, 225);
    --rune-light-color: rgba(34, 67, 142, 0.8);
    text-shadow: 
        0 0 5px rgba(23, 94, 38, 0.8), /* 白色发光 */
        0 0 10px rgba(255, 255, 255, 0.6), /* 更模糊的白色发光 */
        0 0 15px rgb(78, 238, 15), /* 蓝色发光 */
        0 0 20px rgb(32, 170, 106); /* 更模糊的蓝色发光 */
}

```

(But sometimes there are some text that won't change, do you have any clue?)
